name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: Install buf
        run: |
          go install github.com/bufbuild/buf/cmd/buf@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Install frontend deps
        run: pnpm -C frontend install

      - name: Generate code
        run: pnpm run generate

      - name: Build
        run: pnpm run build

      - name: Backend tests
        run: pnpm -C backend test

      - name: Upload backend coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage.out
          if-no-files-found: warn

      - name: Frontend lint
        run: pnpm -C frontend lint